import type { Metadata } from "next";
import { Kumbh_Sans, Inter } from "next/font/google";
import "./globals.css";
import { Footer, Navbar } from "@/components";


const kumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-kumbh-sans",
  weight: ["300", "400", "600", "700"], // optional
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["300", "400", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kumbhSans.variable} ${inter.variable}`}>
        <Navbar/>
        <main>
          {children}
        </main>
      <Footer/>
      </body>
    </html>
  );
}
